const rejections=require('../../../../../../Rejections/Rejections')
async function totalrejections()
{
 await rejections.RJT2_Rejection()
 await rejections.RJT3_Rejection()
 await rejections.RJT4_Rejection()
 await rejections.RJT14_Rejection()
 await rejections.RJT16_Rejection()
 await rejections.RJT17_Rejection()
 await rejections.RJT18_Rejection()
 await rejections.RJT19_Rejection()
 await rejections.RJT20_Rejection()
 await rejections.RJT21_Rejection()
 await rejections.RJT28_OC_Rejection()
}
totalrejections()